### ISSUE TITLE
Left Trigger vs Right Trigger

### ISSUE THREAD

**Issue by funinvegas** [pottedmeat7/OpenVR-WalkInPlace#22]
Thanks a ton for fixing the movement while not holding the configured button.  That is working great.
That being fixed exposed the next issue we are hitting.  Left trigger vs Right trigger.

Specifically for ViveCraft, most the buttons already do something important.  The left trigger was one of the few unassigned controls.  So we selected trigger as the move button.  The problem is Walk-In-Place is responding to both triggers, and the right trigger is attack/work.  So I have to hold perfectly still while chopping a tree to keep from moving (sometimes falling off the top of the tree).

So this is more of a feature request than a bugfix I guess.  But need a way to select which controller has the button input.  The controller select at the top I think is only impacting the controler Walk-In-Place uses to inject movement.

Thanks,
Josh.

**Comment by pottedmeat7** [comment]
Yeah this is somewhat tough issue to solve. I let it be either button similarly because there are different uses for the same buttons on different controllers.
I could use the controller selection that is used for movement but that might not be correct in some cases so I think another dropdown for which controller the button is on would be better but a checkbox to just use 1 controller would be easier. 
I will look at the UI and figure out a way to put that as an option.

**Comment by pottedmeat7** [comment]
@funinvegas Try the latest release. I added a drop down to select the controller. Hope everything else is working with this system.
